---
# assign variables to all nodes in the inventory 

ansible_user: cvpadmin            #user for nodes access defined in your ACT topology
ansible_password: arista123       #password for nodes access defined in your ACT topology
ansible_sudo_pass: arista123      #should be the same as ansible_password be default, change if you set a different one

# github data
github_account: arista-netdevops-community    # github account or organixation
github_repo: AVD-CI-Demo                      # repository
